#!/usr/bin/env python3
"""Embed css/*.css and js/*.js into C sources for md-convert."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


THEMES = ("gfm", "teal", "vermillion")
SCRIPTS = (
    ("highlight", "highlight.js"),
    ("copy_wechat", "copy-wechat.js"),
)


def emit_string_const(name: str, data: bytes, per_line: int = 16) -> str:
    """Emit a null-terminated unsigned char array (UTF-8 safe)."""
    lines = [f"const char {name}[] = {{"]
    row: list[str] = []
    for b in data:
        row.append(f"0x{b:02x}")
        if len(row) >= per_line:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    row.append("0x00")
    lines.append("  " + ", ".join(row))
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "-o",
        "--outdir",
        type=Path,
        required=True,
        help="Directory for embedded_assets.c / .h",
    )
    ap.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="converter/ root (contains css/ and js/)",
    )
    args = ap.parse_args()

    root: Path = args.root
    outdir: Path = args.outdir
    outdir.mkdir(parents=True, exist_ok=True)

    css_dir = root / "css"
    js_dir = root / "js"

    pieces_c: list[str] = [
        "/* Auto-generated by tools/embed_assets.py — do not edit. */",
        '#include "embedded_assets.h"',
        "",
    ]
    decls_h: list[str] = [
        "/* Auto-generated by tools/embed_assets.py — do not edit. */",
        "#ifndef MD_EMBEDDED_ASSETS_H",
        "#define MD_EMBEDDED_ASSETS_H",
        "",
    ]

    for theme in THEMES:
        path = css_dir / f"{theme}.css"
        if not path.is_file():
            print(f"missing theme CSS: {path}", file=sys.stderr)
            return 1
        data = path.read_bytes()
        name = f"md_theme_{theme}_css"
        decls_h.append(f"extern const char {name}[];")
        pieces_c.append(emit_string_const(name, data))
        pieces_c.append("")

    for sym, filename in SCRIPTS:
        path = js_dir / filename
        if not path.is_file():
            print(f"missing script: {path}", file=sys.stderr)
            return 1
        data = path.read_bytes()
        name = f"md_js_{sym}"
        decls_h.append(f"extern const char {name}[];")
        pieces_c.append(emit_string_const(name, data))
        pieces_c.append("")

    decls_h.extend(
        [
            "",
            "/* Return embedded CSS for theme name (gfm/teal/vermillion), or NULL. */",
            "const char *md_theme_css(const char *name);",
            "",
            "#endif",
            "",
        ]
    )

    pieces_c.extend(
        [
            "#include <string.h>",
            "",
            "const char *md_theme_css(const char *name)",
            "{",
            "    if (!name || !name[0])",
            "        return md_theme_gfm_css;",
            '    if (strcmp(name, "gfm") == 0)',
            "        return md_theme_gfm_css;",
            '    if (strcmp(name, "teal") == 0)',
            "        return md_theme_teal_css;",
            '    if (strcmp(name, "vermillion") == 0)',
            "        return md_theme_vermillion_css;",
            "    return NULL;",
            "}",
            "",
        ]
    )

    (outdir / "embedded_assets.h").write_text("\n".join(decls_h), encoding="utf-8")
    (outdir / "embedded_assets.c").write_text("\n".join(pieces_c), encoding="utf-8")
    print(f"wrote {outdir / 'embedded_assets.c'} and .h")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
